# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Score',
            field=models.IntegerField(null=True),
        ),
    ]
