# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusys', '0002_auto_20170425_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Cnature',
            field=models.CharField(default='必修课', max_length=20),
            preserve_default=False,
        ),
    ]
